#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

generated_at="$(date -u +"%Y-%m-%d %H:%M UTC")"
mkdir -p docs

{
  echo "# Development Log"
  echo
  echo "- Generated by \`DOCS_AI\`"
  echo "- Updated at: ${generated_at}"
  echo
  echo "## Recent Repository Activity"
  echo
  git log --date=short --pretty=format:'- %ad | %h | %s' -n 20
  echo
} > docs/dev-log.md
