#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

: "${OWNER:?OWNER is required}"
: "${REPOS:?REPOS is required}"
generated_at="$(date -u +"%Y-%m-%d %H:%M UTC")"
api_root="https://api.github.com/repos"
mkdir -p docs

{
  echo "# Daily Status Board"
  echo
  echo "- Generated by \`SUPERVISOR_AI\`"
  echo "- Updated at: ${generated_at}"
  echo
  echo "## Today"
  echo

  for repo in ${REPOS}; do
    curl_args=(
      -fsSL
      -H "Accept: application/vnd.github+json"
    )

    if [[ -n "${GITHUB_TOKEN:-}" ]]; then
      curl_args+=(-H "Authorization: Bearer ${GITHUB_TOKEN}")
    fi

    response="$(curl "${curl_args[@]}" "${api_root}/${OWNER}/${repo}/commits?per_page=1" 2>/dev/null || true)"

    if [[ -z "${response}" ]] || [[ "$(printf '%s' "${response}" | jq -r 'type')" != "array" ]]; then
      echo "- ${repo}: repository not available yet."
      continue
    fi

    count="$(printf '%s' "${response}" | jq 'length')"
    if [[ "${count}" -eq 0 ]]; then
      echo "- ${repo}: no commits found."
      continue
    fi

    latest_message="$(printf '%s' "${response}" | jq -r '.[0].commit.message' | head -n 1)"
    latest_date="$(printf '%s' "${response}" | jq -r '.[0].commit.author.date' | cut -d'T' -f1)"
    latest_sha="$(printf '%s' "${response}" | jq -r '.[0].sha[0:7]')"

    echo "- ${repo}: latest commit ${latest_sha} on ${latest_date} - ${latest_message}"
  done

  echo
  echo "## Notes"
  echo
  echo "- This board is generated from the latest visible commit of each member repository."
} > docs/daily-status-board.md
